#define PORT_DRIVE_FRONT_LEFT 1
#define PORT_DRIVE_BACK_LEFT 2
#define PORT_DRIVE_FRONT_RIGHT 3
#define PORT_DRIVE_BACK_RIGHT 4

#define PORT_INTAKE_LEFT 6
#define PORT_INTAKE_RIGHT 7

#define PORT_BARREL_FRONT_LEFT 8
#define PORT_BARREL_FRONT_RIGHT 9
#define PORT_BARREL_BACK 10
